taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls', namespace='tasks')), #Including tasks URLs with a namespace
]

taskmanager/tasks/urls.py
from django.urls import path, register_converter
from django.views.generic import TemplateView

from . import converters
from .views import (
    TaskCreateView,
    TaskDeleteView,
    TaskDetailView,
    TaskListView,
    TaskUpdateView,
    create_task_on_sprint,
    task_by_date,
    task_home,
)

app_name = "tasks"
register_converter(converters.DateConverter, 'yyyymmdd')
handler404 = "tasks.views.custom_404"


urlpatterns = [
    path("", TemplateView.as_view(template_name="tasks/home.html"), name="home"),
    path("tasks/home/", task_home, name="task-home"),
    path("help/", TemplateView.as_view(template_name="tasks/help.html"), name="help"),
    path("tasks/", TaskListView.as_view(), name="task-list"),  # GET
    path("tasks/new/", TaskCreateView.as_view(), name="task-create"),  # POST
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),  # GET
    path(
        "tasks/<int:pk>/edit/", TaskUpdateView.as_view(), name="task-update"
    ),  # PUT/PATCH
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"
    ),  # DELETE
    path('tasks/<yyyymmdd:date>/', task_by_date, name='task-get-by-date'),
    path(
        "tasks/sprint/add_task/<int:pk>/",
        create_task_on_sprint,
        name="task-add-to-sprint",
    ),
]

taskmanager/tasks/models.py
from django.contrib.auth.models import User
from django.db import models


class VersionMixing:
    version = models.IntegerField(default=0)


class Task(models.Model, VersionMixing):
    STATUS_CHOICES = [
        ("UNASSIGNED", "Unassigned"),
        ("IN_PROGRESS", "In Progress"),
        ("DONE", "Completed"),
        ("ARCHIVED", "Archived"),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=False, default="")
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="UNASSIGNED",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        User, related_name="created_tasks", on_delete=models.CASCADE
    )
    owner = models.ForeignKey(
        User, related_name="owned_tasks", on_delete=models.SET_NULL, null=True
    )
    version = models.IntegerField(default=0)

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(status="UNASSIGNED")
                | models.Q(status="IN_PROGRESS")
                | models.Q(status="DONE")
                | models.Q(status="ARCHIVED"),
                name="status_check",
            ),
        ]


class Epic(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        User, related_name="created_epics", on_delete=models.CASCADE
    )
    tasks = models.ManyToManyField("Task", related_name="epics", blank=True)
    # This field might be used to denote the progress of the epic
    completion_status = models.FloatField(default=0.0)


class Sprint(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        User, related_name="created_sprints", on_delete=models.CASCADE
    )
    tasks = models.ManyToManyField("Task", related_name="sprints", blank=True)
    # The epic to which this sprint is contributing
    epic = models.ForeignKey(
        Epic, related_name="sprints", on_delete=models.CASCADE, null=True, blank=True
    )

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(end_date__gt=models.F("start_date")),
                name="end_date_after_start_date",
            ),
        ]

taskmanager/tasks/views.py
# Code for tasks/views.py
from datetime import date

from django.http import (
    Http404,
    HttpRequest,
    HttpResponse,
    HttpResponseRedirect,
    JsonResponse,
)
from django.shortcuts import redirect, render
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from . import services
from .mixins import SprintTaskMixin
from .models import Task


class TaskListView(ListView):
    model = Task
    template_name = "task_list.html"
    context_object_name = "tasks"


class TaskDetailView(DetailView):
    model = Task
    template_name = "tasks/task_detail.html"
    context_object_name = "task"


class TaskCreateView(CreateView):
    model = Task
    template_name = "tasks/task_form.html"
    fields = ("title", "description")

    def get_success_url(self):
        return reverse_lazy("tasks:task-detail", kwargs={"pk": self.object.id})


class TaskUpdateView(SprintTaskMixin, UpdateView):
    model = Task
    template_name = "tasks/task_form.html"
    fields = ("title", "description")

    def get_success_url(self):
        return reverse_lazy("tasks:task-detail", kwargs={"pk": self.object.id})


class TaskDeleteView(DeleteView):
    model = Task
    template_name = "tasks/task_confirm_delete.html"
    success_url = reverse_lazy("tasks:task-list")


def task_home(request):
    return redirect(reverse("tasks:ask-list"))


def task_by_date(request: HttpRequest, date: date) -> HttpResponse:
    template = loader.get_template("task_list.html")
    tasks = services.get_task_by_date(date)
    context = {"tasks": tasks, "by_date": date}  # Add the date to context
    html = template.render(context, request)
    return HttpResponse(html)


def create_task_on_sprint(request: HttpRequest, sprint_id: int) -> HttpResponseRedirect:
    if request.method == "POST":
        task_data: dict[str, str] = {
            "title": request.POST["title"],
            "description": request.POST.get("description", ""),
            "status": request.POST.get("status", "UNASSIGNED"),
        }
        task = services.create_task_and_add_to_sprint(
            task_data, sprint_id, request.user
        )
        return redirect("tasks:task-detail", task_id=task.id)
    raise Http404("Not found")


def claim_task_view(request, task_id):
    user_id = (
        request.user.id
    )  # Assuming you have access to the user ID from the request

    try:
        services.claim_task(user_id, task_id)
        return JsonResponse({"message": "Task successfully claimed."})
    except Task.DoesNotExist:
        return HttpResponse("Task does not exist.", status=404)
    except services.TaskAlreadyClaimedException:
        return HttpResponse("Task is already claimed or completed.", status=400)


def custom_404(request, exception):
    return render(request, "404.html", {}, status=404)

taskmanager/templates/tasks/_footer.html
<footer class="footer mt-auto py-3 bg-light text-center">
    <div class="container">
        <a href="{% url 'tasks:help' %}" class="text-dark">Help</a>
    </div>
</footer>

taskmanager/templates/tasks/_header.html
<header class="d-flex justify-content-between align-items-center p-3">
    <!-- Left side -->
    <div>
        <a href="{% url 'tasks:task-create' %}" class="btn btn-primary" role="button">Create</a>
    </div>


    <!-- Right side -->
    <div class="d-flex">
        <input type="text" class="form-control" id="search" placeholder="Search">
        <button type="button" class="btn btn-success ml-2">Search</button>
    </div>
</header>

taskmanager/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document Title</title>
    <!-- CSS files -->
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">    <!-- <link rel="stylesheet" href="styles.css"> -->
</head>
<body>

    {% include "tasks/_header.html" %}
    <main class="d-flex flex-column justify-content-center align-items-center"></main>
        <div class="text-center">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    {% include "tasks/_footer.html" %}
    <!-- JS files -->
    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <!-- <script src="script.js"></script> -->
</body>
</html>

taskmanager/templates/tasks/help.html
{% extends "tasks/base.html" %}

{% block content %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">
                Help Page
            </div>
            <div class="card-body">
                <h5 class="card-title">What is a task manager?</h5>
                <p class="card-text">A task management system is software that helps users organize and track the progress of tasks.</p>
            </div>
        </div>
    </div>
{% endblock %}

taskmanager/templates/tasks/home.html
{% extends "tasks/base.html" %}

{% block content %}
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ...</p>
{% endblock %}

taskmanager/templates/tasks/task_confirm_delete.html
{% extends "tasks/base.html" %}

{% block content %}
  <h1>Delete Task</h1>
  <p>Are you sure you want to delete the task "{{ task.name }}"?</p>
  <form method="post">
  {% csrf_token %}
  <button type="submit">Yes, delete</button>
  </form>
  <a href="{% url 'tasks:task-detail' task.id %}">No, take me back</a>
{% endblock %}

taskmanager/templates/tasks/task_detail.html
{% extends "tasks/base.html" %}

{% block content %}
  <h1>{{ task.title }}</h1>
  <h2>Description</h2>
  <p>{{ task.description }}</p>
  <a href="{% url 'tasks:task-update' task.id %}">Edit</a>
  <a href="{% url 'tasks:task-delete' task.id %}">Delete</a>
  <a href="{% url 'tasks:task-list' %}">List</a>
{% endblock %}

taskmanager/templates/tasks/task_form.html
{% extends "tasks/base.html" %}

{% block content %}
  <h1>New Task</h1>
  <form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
  <a href="{% url 'tasks:task-list' %}">No, take me back</a>
  </form>
{% endblock %}

taskmanager/templates/tasks/task_list.html
{% extends "tasks/base.html" %}

{% block content %}
  <h1>Task List</h1>
  <ul>
  {% for task in tasks %}
    <li class="list-unstyled">
      <a href="{% url 'tasks:task-detail' task.id %}">{{ task.title }}</a>
    </li>
  {% empty %}
    <li>No tasks available.</li>
  {% endfor %}
  </ul>
{% endblock %}